### ISSUE TITLE
Changing default Placeholder value shows some other characters

### ISSUE THREAD

**Issue by manutdkid77** [CrossGeeks/ClearableDatePickerSample#1]
Thanks for the awesome control, its helped me a lot in my project :+1: . However I faced I an issue:

Xamarin Forms Version :  2.3.4.267
Android OS Version :  6.0.1

I wanted to change the default placeholder empty value to text like "Please select a date", 

```
<StackLayout VerticalOptions="FillAndExpand">
            <local1:NullableDatePicker NullableDate="{Binding MyDate}" PlaceHolder="Please select a date"></local1:NullableDatePicker>
        </StackLayout>
```

but when the page opens up it shows some other characters 

![screenshot_20170828-054300](https://user-images.githubusercontent.com/14297705/29755323-fab88ae4-8bb3-11e7-8322-f87f2cbc0736.png)

Later if I click on Datepicker and select Clear, the placeholder shows the correct text.

![screenshot_20170828-054308](https://user-images.githubusercontent.com/14297705/29755326-12b109d2-8bb4-11e7-8c0e-aa2f17f719ed.png)

**Comment by rdelrosario** [comment]
Fixed on https://github.com/CrossGeeks/ClearableDatePickerSample/commit/3ce85a27ea31036eb1fdbee723296290eb25638e
