### ISSUE TITLE
Clear button click event 

### ISSUE THREAD

**Issue by nmano2188** [CrossGeeks/ClearableDatePickerSample#4]
How to raise DateSelected event on clear button click ?

**Comment by SatanEnglish** [comment]
Not sure this is valid as your not selecting a date.
Just use binding and on value change decide what to do.
This way you can check when date changes to null.

**Comment by nmano2188** [comment]
Here i need to set value to date2 based on date1 value. 
And also
If date1 is cleared also need to clear date2 on date1 clear event.
This is what i want and can't do this now. Any suggestions?

**Comment by SatanEnglish** [comment]
var startPicker = new NullableDatePicker()
        {
            NullableDate = null,
            Format = "d MMMM"
        };
        startPicker.BindingContext = _viewModel.BirthingModel;
        startPicker.SetBinding(NullableDatePicker.NullableDateProperty, "BirthingStart");

// Birth Model bit

        private DateTime? _birthingStart;
        public DateTime? BirthingStart
        {
            get
            {
                return _birthingStart;
            }

            set
            {
               // OnProperty Change this ones Prism example
                if (SetProperty(ref _birthingStart, value))
                {
                  if(value == null) SomeOtherDate = null;
                }
            }
        }

Hope this helps this is a Forms example but you should get the idea

**Comment by SatanEnglish** [comment]
@nmano2188 
Did this fix your issue?

**Comment by manonaga2188** [comment]
@SatanEnglish  I will try and let you know. Thanks
